; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[platformio]
; Arduino IDEでもビルドできるよう、ソースはFaces_Calcフォルダのまま使用する
src_dir = Faces_Calc
default_envs = m5stack-basic

; M5Stack Basic
[env:m5stack-basic]
platform = espressif32@6.12.0
board = m5stack-core-esp32
framework = arduino
monitor_speed = 115200
upload_speed = 1500000
lib_deps =
    m5stack/M5Unified
    tobozo/M5Stack-SD-Updater@^1.2.8
